package types

import "time"

type Result struct {
	StateName  string  `json:"stateName"`
	Democrat   float64 `json:"democrat"`
	Republican float64 `json:"republican"`
	Other      float64 `json:"other"`
	Winner     string  `json:"winner"`
}

type Event struct {
	ID               string    `json:"id"`
	Ticker           string    `json:"ticker"`
	Slug             string    `json:"slug"`
	Title            string    `json:"title"`
	Description      string    `json:"description"`
	ResolutionSource string    `json:"resolutionSource"`
	StartDate        time.Time `json:"startDate"`
	CreationDate     time.Time `json:"creationDate"`
	EndDate          time.Time `json:"endDate"`
	Image            string    `json:"image"`
	Icon             string    `json:"icon"`
	Active           bool      `json:"active"`
	Closed           bool      `json:"closed"`
	Archived         bool      `json:"archived"`
	New              bool      `json:"new"`
	Featured         bool      `json:"featured"`
	Restricted       bool      `json:"restricted"`
	Liquidity        float64   `json:"liquidity"`
	Volume           float64   `json:"volume"`
	OpenInterest     int       `json:"openInterest"`
	SortBy           string    `json:"sortBy"`
	PublishedAt      string    `json:"published_at"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
	CommentsEnabled  bool      `json:"commentsEnabled"`
	Competitive      float64   `json:"competitive"`
	Volume24Hr       float64   `json:"volume24hr"`
	FeaturedImage    string    `json:"featuredImage"`
	EnableOrderBook  bool      `json:"enableOrderBook"`
	LiquidityClob    float64   `json:"liquidityClob"`
	Sync             bool      `json:"_sync"`
	NegRisk          bool      `json:"negRisk"`
	NegRiskMarketID  string    `json:"negRiskMarketID"`
	CommentCount     int       `json:"commentCount"`
	Markets          []struct {
		ID                           string    `json:"id"`
		Question                     string    `json:"question"`
		ConditionID                  string    `json:"conditionId"`
		Slug                         string    `json:"slug"`
		ResolutionSource             string    `json:"resolutionSource"`
		EndDate                      time.Time `json:"endDate"`
		Liquidity                    string    `json:"liquidity"`
		StartDate                    time.Time `json:"startDate"`
		Fee                          string    `json:"fee"`
		Image                        string    `json:"image"`
		Icon                         string    `json:"icon"`
		Description                  string    `json:"description"`
		Outcomes                     string    `json:"outcomes"`
		OutcomePrices                string    `json:"outcomePrices"`
		Volume                       string    `json:"volume"`
		Active                       bool      `json:"active"`
		MarketType                   string    `json:"marketType"`
		Closed                       bool      `json:"closed"`
		MarketMakerAddress           string    `json:"marketMakerAddress"`
		CreatedAt                    time.Time `json:"createdAt"`
		UpdatedAt                    time.Time `json:"updatedAt"`
		WideFormat                   bool      `json:"wideFormat"`
		New                          bool      `json:"new"`
		Featured                     bool      `json:"featured"`
		SubmittedBy                  string    `json:"submitted_by"`
		Archived                     bool      `json:"archived"`
		ResolvedBy                   string    `json:"resolvedBy"`
		Restricted                   bool      `json:"restricted"`
		GroupItemTitle               string    `json:"groupItemTitle"`
		GroupItemThreshold           string    `json:"groupItemThreshold"`
		QuestionID                   string    `json:"questionID"`
		EnableOrderBook              bool      `json:"enableOrderBook"`
		OrderPriceMinTickSize        float64   `json:"orderPriceMinTickSize"`
		OrderMinSize                 int       `json:"orderMinSize"`
		VolumeNum                    float64   `json:"volumeNum"`
		LiquidityNum                 float64   `json:"liquidityNum"`
		EndDateIso                   string    `json:"endDateIso"`
		StartDateIso                 string    `json:"startDateIso"`
		HasReviewedDates             bool      `json:"hasReviewedDates"`
		CommentsEnabled              bool      `json:"commentsEnabled"`
		Volume24Hr                   float64   `json:"volume24hr,omitempty"`
		SecondsDelay                 int       `json:"secondsDelay"`
		ClobTokenIds                 string    `json:"clobTokenIds"`
		UmaBond                      string    `json:"umaBond"`
		UmaReward                    string    `json:"umaReward"`
		FpmmLive                     bool      `json:"fpmmLive"`
		Volume24HrClob               float64   `json:"volume24hrClob,omitempty"`
		VolumeClob                   float64   `json:"volumeClob"`
		LiquidityClob                float64   `json:"liquidityClob"`
		MakerBaseFee                 int       `json:"makerBaseFee"`
		TakerBaseFee                 int       `json:"takerBaseFee"`
		CustomLiveness               int       `json:"customLiveness"`
		AcceptingOrders              bool      `json:"acceptingOrders"`
		NegRisk                      bool      `json:"negRisk"`
		NegRiskMarketID              string    `json:"negRiskMarketID"`
		NegRiskRequestID             string    `json:"negRiskRequestID"`
		NotificationsEnabled         bool      `json:"notificationsEnabled"`
		Sync                         bool      `json:"_sync"`
		Creator                      string    `json:"creator"`
		Ready                        bool      `json:"ready"`
		Funded                       bool      `json:"funded"`
		Cyom                         bool      `json:"cyom"`
		Competitive                  float64   `json:"competitive"`
		PagerDutyNotificationEnabled bool      `json:"pagerDutyNotificationEnabled"`
		Approved                     bool      `json:"approved"`
		ClobRewards                  []struct {
			ID               string `json:"id"`
			ConditionID      string `json:"conditionId"`
			AssetAddress     string `json:"assetAddress"`
			RewardsAmount    int    `json:"rewardsAmount"`
			RewardsDailyRate int    `json:"rewardsDailyRate"`
			StartDate        string `json:"startDate"`
			EndDate          string `json:"endDate"`
		} `json:"clobRewards"`
		RewardsMinSize      int     `json:"rewardsMinSize"`
		RewardsMaxSpread    float64 `json:"rewardsMaxSpread"`
		Spread              float64 `json:"spread"`
		OneDayPriceChange   float64 `json:"oneDayPriceChange"`
		LastTradePrice      float64 `json:"lastTradePrice"`
		BestBid             float64 `json:"bestBid"`
		BestAsk             float64 `json:"bestAsk"`
		AutomaticallyActive bool    `json:"automaticallyActive"`
		ClearBookOnStart    bool    `json:"clearBookOnStart"`
		SeriesColor         string  `json:"seriesColor,omitempty"`
		ShowGmpSeries       bool    `json:"showGmpSeries,omitempty"`
		ShowGmpOutcome      bool    `json:"showGmpOutcome,omitempty"`
	} `json:"markets"`
	Tags []struct {
		ID          string    `json:"id"`
		Label       string    `json:"label"`
		Slug        string    `json:"slug"`
		Sync        bool      `json:"_sync"`
		ForceShow   bool      `json:"forceShow,omitempty"`
		PublishedAt string    `json:"publishedAt,omitempty"`
		UpdatedBy   int       `json:"updatedBy,omitempty"`
		CreatedAt   time.Time `json:"createdAt,omitempty"`
		UpdatedAt   time.Time `json:"updatedAt,omitempty"`
		ForceHide   bool      `json:"forceHide,omitempty"`
	} `json:"tags"`
	Cyom                bool   `json:"cyom"`
	ShowAllOutcomes     bool   `json:"showAllOutcomes"`
	ShowMarketImages    bool   `json:"showMarketImages"`
	EnableNegRisk       bool   `json:"enableNegRisk"`
	AutomaticallyActive bool   `json:"automaticallyActive"`
	GmpChartMode        string `json:"gmpChartMode"`
}
